modLoader="javafml" #mandatory
license="GNU V3"
loaderVersion="[43,)" #mandatory (26 is current forge version)

# A URL to refer people to when problems occur with this mod
issueTrackerURL="https://github.com/ArtixAllMighty/JustFashion/issues" #optional

logoFile="banner.png" #optional

[[mods]] #mandatory

modId="fashion" #mandatory

version="${file.jarVersion}" #mandatory

displayName="Fashion Mod" #mandatory

displayURL="https://www.curseforge.com/minecraft/mc-mods/just-fashion" #optional

authors="Subaraki" #optional

description='''
Have some fashion on your player !
Pop in de wardrobe and pick from any base items provided, or make your own resourcepack and enjoy being
F A B U L O U S
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
# Here's another dependency
[[dependencies.fashion]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.fashion]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[43,)" #mandatory
    ordering="NONE"
    side="BOTH"