modLoader = "lowcodefml"
license = "GNU V3"
loaderVersion="[40,)"
logoFile = "banner.png" #optional
[[mods]]
modId = "suits_fashion_pack"
version = "2.0.0"
displayName = "Suits+ [fashion pack]"
description = '''
base suits for JustFashion'''